import Head from 'next/head';
// Components
import { Ads, FeaturedProperties, Hero, MeetTheTeam, Testemonials } from '../components';
import DefaultLayout from '../layouts/DefaultLayout';

export default function Home({ featuredProperties }) {
  return (
    <>
      <Head>
        <title>Real Estate Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <DefaultLayout>
        <Hero />
        <FeaturedProperties featuredProperties={featuredProperties}/>
        <MeetTheTeam />
        <Ads />
        <Testemonials />
      </DefaultLayout>
      
    </>
  )
};

export const getStaticProps = async () => {
  const { hits } = require('../features/data/properties');

  return{
    props: { 
      featuredProperties: hits.slice(0, 6), 
    }
  }
};