import Head from 'next/head';
// Components
import { FeaturedProperties, Header, Hero } from '../components';

export default function Home({ featuredProperties }) {
  return (
    <>
      <Head>
        <title>Real Estate Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <FeaturedProperties featuredProperties={featuredProperties}/>
    </>
  )
};

export const getServerSideProps = async () => {
  const { hits } = require('../features/data/properties');

  return{
    props: { 
      featuredProperties: hits.slice(0, 6), 
    }
  }
}